---
- name: Update web servers
  hosts: ec2
  remote_user: ubuntu

  tasks:
  - name: clone repository
    shell: "rm -rf  hashing-app && git clone https://github.com/jcrisanto/hashing-app.git"

  - name: add node repository
    shell: "curl -s https://deb.nodesource.com/setup_16.x | sudo bash && sudo apt install nodejs -y"

  - name: install pm2
    shell: "sudo npm install pm2 -g"

  - name: run server
    shell: "cd hashing-app/backend && npm i && pm2 start src/start.js"
