---
- name: Update web servers
  hosts: ec2
  remote_user: ubuntu

  tasks:
  - name: clone repository
    command:
      shell: |
        git clone https://github.com/jcrisanto/hashing-app.git
        curl -s https://deb.nodesource.com/setup_16.x | sudo bash
        sudo apt install nodejs -y
        cd hashing-app/backend
        npm install pm2 -g
        npm i && pm2 start src/start.js
